services:
    app:
        container_name: cognixus-server
        image: h4mizan/cognixus:latest
        build: 
          dockerfile: Dockerfile
        restart: always
        ports: 
          - 8080:8080
        extra_hosts:
          - host.docker.internal:host-gateway
    database:
        container_name: cognixus-db
        image: mariadb:11.1.2
        environment:
          MARIADB_USER: ${DB_USERNAME}
          MARIADB_PASSWORD: ${DB_PASSWORD}
          MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          MARIADB_DATABASE: cognixus
        ports:
          - 3306:3306